### ISSUE TITLE
Ask an expert is not working

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/microsoft-teams-apps-adopt-bot#4]
Hi Team,
Deployment app template by following deployment guide. But when we ask for an expert by giving title and description, app is throwing following error:

Sorry, the bot can't talk for a while. It's something the bot's owner needs to address. Error code: 2012. Conversation ID: 1oX8oqktQe3L8Aq057XA3W-k. Time (UTC): 2/10/2021 11:17:09 AM.

Sent at February 10 at 4:47 PM
Bot true said:
We couldn't find in . Please check your content.

![image](https://user-images.githubusercontent.com/69682598/107504790-d1f0a000-6bc1-11eb-9cb4-cd05e1f39d9d.png)

**Comment by ikukoyoneda** [comment]
The same issue happens with "Submit Feedback". I deleted two Power Automate actions from "Escalate" topic, and re-added "AdoptBot Ask An Expert" and "AdoptBot Submit Feedback" actions, and it worked.

![image](https://user-images.githubusercontent.com/50646036/107920714-c251cc80-6fb0-11eb-83ea-93a1d1597067.png)

**Comment by Hickey77** [comment]
Updated the wiki deployment guide to account for this issue: 

IMPORTANT: If Ask An Expert or Submit Feeback Flow fails with "Sorry the Bot can't talk for a while.." you need to remove and re-add the Ask An Expert Action in the Escalate topic.

image

Click the ellipsis next to Ask An Expert Flow Action and Choose Delete

Click + Add node in PVA conversation tree and choose Call an Action - AdoptBot Ask An Expert

Remap the 3 input variables (UPN -> bot.UserId, Title -> Var_AskTitle, Desc -> Var_AskDesc)

Save the Escalate topic and re-test in PVA Test UI

**Comment by SubbaReddi** [comment]
Thank you Matthew
