### ISSUE TITLE
Power Automate Import Problem

### ISSUE THREAD

**Issue by kozakjanos** [OfficeDev/microsoft-teams-apps-adopt-bot#5]
i've tried import the AdoptionBotPVA2021_1_0_0_5.zip to Microsoft Powre Automate, but not working. I've tried 3 separeted M365 tenant.
![import_package_error](https://user-images.githubusercontent.com/43601136/112646567-ec1bd000-8e47-11eb-925e-c5bf5baef903.png)

**Comment by Hickey77** [comment]
@kozakjanos Sorry for the delay.  Can you try the latest zip that was just posted?  Working though some issues with Engineering.

Imports works now.  Known issues - wonder if you see these as well:
1. During import will see "This version of the solution package is already installed" - ignore
![image](https://user-images.githubusercontent.com/54556057/114104286-92c88d80-9898-11eb-99a8-7e1298ffe25a.png)
2. Import may looks like it did not finish - Currently Importing solution "Adoption Bot 2021" - refresh after a few minutes and is actually imported 
![image](https://user-images.githubusercontent.com/54556057/114104342-aaa01180-9898-11eb-9822-a04d0e6d1b05.png)
3. Per the wiki, you need to remove and re-add the flows in PVA Escalate topic if you get this error
![image](https://user-images.githubusercontent.com/54556057/114104440-dc18dd00-9898-11eb-9e30-e29c1eb6b0e7.png)

**Comment by koubyak** [comment]
@Hickey77 , I'm facing the same issue on my side. 
I can import the latest package in a dev env. but not in the Teams Env.
Nothing is shown in the Solutions History and shown in the solution, even after an hour

**Comment by Hickey77** [comment]
Yes, issue 2?  Did you refresh and check in the default solution?  For me, the Bot and Topics are there.  The Flows are also imported but don't show initially.  You can see them in Power App for Teams App eventually.

Can you explain cannot import in the Teams Env?  Import never finishes or errors out?

**Comment by koubyak** [comment]
ok, it was longer than an hour but they are now in the default solution
Thanks for your answer ;)

**Comment by Hickey77** [comment]
Cool, will continue to work on known issues.  Does actually take a few mins to import, but never lets you know its done 🤪

**Comment by kcullen8** [comment]
@Hickey77 
I seem to be getting Issue 2, but nothing ever gets installed. I've tried a few "Teams" environments now.

I do however get an error in the history: 8004801E.

Import failed: {"statuscode":400,"statusdescription":"Bad Request","errors":[{"code":9103,"message":"An exception was thrown while activating BotDesigner.ManagementService.BotManagement.BotManagementService."}]}

I am using a dev tenant, which I'm trying to setup for some demos, if that is pertinent.

Cheerd

**Comment by Hickey77** [comment]
Reauthored the deployment instructions leveraging V2 Import now avaible in Power App for Teams.  Should be faster and less buggy.  Please test out and LMK,

**Comment by kcullen8** [comment]
Thanks. I've given that a try and got the same error: 
An exception was thrown while activating BotDesigner.ManagementService.BotManagement.BotManagementService

I'm quite new to this but I'm wondering if there is something to do with me using a Dev Tenant. I've had a look in the Pwr Admin center, and there is a message that the tenant is over capacity.
Under "Capacity-Dataverse", I only have the default environment which has 1gb and under "Microsoft Teams", I have two environments, one for the "Adoption Bot" and one for "O365 Champions Network", both with 512Mb of 2Gb.

I can't see how I can reduce data, or increase the capacity, if that is required.

[AdoptionBot2021_1_0_0_3.zip_import.zip](https://github.com/OfficeDev/microsoft-teams-apps-adopt-bot/files/6339708/AdoptionBot2021_1_0_0_3.zip_import.zip)

**Comment by Hickey77** [comment]
@kcullen8 - not sure what you mean by dev tenant.  One idea is use a trial tenant and see if the same error persists:  https://signup.microsoft.com/signup/logout?offerid=B07A1127-DE83-4a6d-9F85-2C104BDAE8B4&dl=ENTERPRISEPACK&culture=en-US&country=US&ali=1

Also can you post a screenshot of the error and session details (CRTL + ALT + A in Power Apps for Teams)

**Comment by Hickey77** [comment]
Import problems fixed by moving to v2 Import using Power Apps for Teams
